experiment:
  output_dir: "./exps/"
  checkpoint: ""
  motion_seqs_dir: "assets/sample_motion/export/Taylor_Swift/"
  # subj_id: 1240
  # source_cam_ids: ["C24", "C27"]
  subj_id: 70
  source_cam_ids: ["C18", "C27"]
  env_id: "env_000"
  expr_id: "expr_00000"
  model_name: "exps/releases/lam/lam-20k/step_045500/"
  export_motion_video: false
  audio_source_video: "assets/sample_motion/export/Taylor_Swift/Taylor_Swift.wav"
model:
  transformer_dim: 1024
  transformer_layers: 10
  tf_grad_ckpt: true
  pcl_dim: 1024 
  encoder_grad_ckpt: true
  flame_subdivide_num: 1
  transformer_heads: 16
  latent_query_points_type: "e2e_flame"
  encoder_type: "dinov2_fusion"
  encoder_model_name: "dinov2_vitl14_reg"
  transformer_type: "sd3_cond"
  encoder_feat_dim: 1024
  encoder_freeze: false
  gs_query_dim: 1024
  gs_use_rgb: true
  gs_sh: 3
  gs_mlp_network_config:
    activation: "silu"
    n_hidden_layers: 2
    n_neurons: 512
  gs_xyz_offset_max_step: 0.2
  gs_clip_scaling: 0.01
  scale_sphere: false
  shape_param_dim: 300
  expr_param_dim: 100
  num_source_views: 2
  add_teeth: false

  fix_opacity: false
  fix_rotation: false
  num_gaussians_per_vertex: 5
  is_finetuning: true

  has_disc: false

  teeth_bs_flag: false
  oral_mesh_flag: false       # keep for ModelLAM construction

dataset:
  cafca_subject_ids_val: [70] # 30, 31, 32, 33, 34, 35, 36, 41, 45, 50, 51, 55
  max_tokens_in_ram: 16
  num_of_src_views: 2
  num_of_target_views: 1

training:                      # only fields still referenced in code
  image_size: 512
  finetune_renderer_mlp_only: false