experiment:
  name: "lam_1view_overfitting"
  output_dir: "./exps/finetuned_lam_cafca_renderer_mlp"
  model_name: "exps/releases/lam/lam-20k/step_045500/"

model:
  pretrained_model_name_or_path: "/home/dkonur/LAMpp/exps/releases/lam/lam-20k/step_045500/"
  transformer_dim: 1024
  transformer_layers: 10
  transformer_heads: 16
  transformer_type: "sd3_cond"
  tf_grad_ckpt: true
  encoder_grad_ckpt: true
  encoder_freeze: false
  encoder_type: 'dinov2_fusion'
  encoder_model_name: 'dinov2_vitl14_reg'
  encoder_feat_dim: 1024
  instantiate_encoder: false
  instantiate_transformer: false
  
  latent_query_points_type: "e2e_flame"
  pcl_dim: 1024 
  
  human_model_path: "./model_zoo/human_parametric_models/"
  flame_subdivide_num: 1
  flame_type: "flame"
  
  gs_query_dim: 1024
  gs_use_rgb: true
  gs_sh: 3
  gs_mlp_network_config:
    activation: "silu"
    n_hidden_layers: 2
    n_neurons: 512
  gs_xyz_offset_max_step: 0.2
  gs_clip_scaling: 0.01
  
  shape_param_dim: 10
  expr_param_dim: 10
  
  fix_opacity: false
  fix_rotation: false
  flame_scale: 1.0
  
  add_teeth: false
  teeth_bs_flag: false
  oral_mesh_flag: false
  
  use_mesh_shading: false
  render_rgb: true
  decode_with_extra_info: null
  scale_sphere: false

dataset:
  cafca_subject_ids_train: [30, 31, 32, 33] #, 34, 35, 36, 41, 45
  cafca_subject_ids_val: [55, 49] #, 50, 51,  48
  num_of_src_views: 1
  num_of_target_views: 4 # try 2-3 and increase batch size
  max_tokens_in_ram: 64

training:
  batch_size: 8
  num_epochs: 100
  learning_rate: 1e-5
  device: "cuda"
  save_every_n_epochs: 20
  image_size: 512
  num_workers: 2
  l1_loss_weight: 1.0
  lpips_loss_weight: 1.0
  silhouette_loss_weight: 1.0
  offset_loss_weight: 0.1
  finetune_renderer_mlp_only: True
  validate_every_n_epochs: 1
  num_val_samples_to_log: 1
  num_train_samples_to_log: 1


wandb:
  enabled: true
  project: "lam-1-view-finetuning"
  entity: "gr-lampp"
  run_name: "1-view_overfitting_b8_2workers_alex_wo_gs_net"
  log_every_n_steps: 10
  log_train_images_every_n_steps: 15

profiler:
  is_enabled: false
  log_dir: "./lightning_logs"
